### ISSUE TITLE
In the dcnn examples, nLayers, which is only used to derive the persistent constant nInputs, is executed on every function call.

### ISSUE THREAD

**Issue by nixir** [msiplab/SaivDr#12]
The dcnn example for resolving delay in calling layer names (#7fbb1f38) defined a persistent variable, nInputs, that is fixed and deterministic on the first execution of a function. 
The derivation of the nLayers variable, which is used only to derive nInputs, is now performed for each function call, which slows down the calculation.

**Comment by shodimaggio** [comment]
Thanks.
